routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(["as" => "admin." , "namespace" => "Admin" , "prefix" => "admin/" , "middleware" => ["auth" , "admin"]],function (){

	Route::get("" , "DashboardController@index")->name("dashboard");

    //َAdmin Users Routes//
    Route::group(["as" => "users." , "prefix" => "users/"] , function () {
        Route::get("" , "UserController@index")->name("list");
        Route::get("create" , "UserController@create")->name("create");
        Route::post("create" , "UserController@store")->name("store");
        Route::get("{user}/edit" , "UserController@edit")->name("edit");
        Route::get("{user}/packages" , "UserController@packages_list")->name("packages");
        Route::patch("{user}/update" , "UserController@update")->name("update");
        Route::delete("{user}/delete" , "UserController@destroy")->name("delete");
    });

    //Admin Files Routes//
    Route::group(["as" => "files." , "prefix" => "files/"] , function () {
        Route::get("", "FileController@index")->name("list");
        Route::get("create", "FileController@create")->name("create");
        Route::post("create", "FileController@store")->name("store");
        Route::get("{file}/edit", "FileController@edit")->name("edit");
        Route::patch("{file}/update", "FileController@update")->name("update");
        Route::delete("{file}/delete", "FileController@destroy")->name("delete");
    });

    //Admin Plans Routes//
    Route::group(["as" => "plans." , "prefix" => "plans/"] , function () {
        Route::get("" , "PlanController@index")->name("list");
        Route::get("create" , "PlanController@create")->name("create");
        Route::post("create" , "PlanController@store")->name("store");
        Route::get("{plan}/edit" , "PlanController@edit")->name("edit");
        Route::patch("{plan}/update" , "PlanController@update")->name("update");
        Route::delete("{plan}/delete" , "PlanController@destroy")->name("delete");
    });

    //Admin Categories Routes//
    Route::group(["as" => "categories." , "prefix" => "categories/"] , function () {
        Route::get("" , "CategoryController@index")->name("list");
        Route::get("create" , "CategoryController@create")->name("create");
        Route::post("create" , "CategoryController@store")->name("store");
        Route::get("{category}/edit" , "CategoryController@edit")->name("edit");
        Route::patch("{category}/update" , "CategoryController@update")->name("update");
        Route::delete("{category}/delete" , "CategoryController@destroy")->name("delete");
    });

    //Admin Packages Routes//
    Route::group(["as" => "packages." , "prefix" => "packages/"] , function () {
        Route::get("" , "PackageController@index")->name("list");
        Route::get("create" , "PackageController@create")->name("create");
        Route::post("create" , "PackageController@store")->name("store");
        Route::get("{package}/edit" , "PackageController@edit")->name("edit");
        Route::patch("{package}/update" , "PackageController@update")->name("update");
        Route::delete("{package}/delete" , "PackageController@destroy")->name("delete");

        Route::get('sync_files/{package}', "PackageController@sync_file")->name("sync_file_view");
        Route::post('sync_files/{package}', "PackageController@sync")->name("sync_file");
    });

    //Admin Plans Routes//
    Route::group(["as" => "payments." , "prefix" => "payments/"] , function () {
        Route::get("", "PaymentController@index")->name("list");
    });
});

Auth::routes();
Route::group(["as" => "app." , "namespace" => "App"] , function (){
	Route::middleware('guest')->group(function (){
	Route::get("Account/login" ,"AuthController@loginView")->name("login.view");
	Route::get("Account/register" ,"AuthController@registerView")->name("register.view");
	Route::post("Account/login" ,"AuthController@login")->name("login.action");
	Route::post("Account/register" ,"AuthController@register")->name("register.action");
});
	Route::get("Account/logout" ,"AuthController@logout")->name("logout.action");

    Route::get("" , "HomeController@index")->name("home");

    Route::get("/plans" , "PlanController@index")->name("plans.index");

    Route::get("/subscribe/{plan}" , "SubscribeController@subscribe")->name("subscribes.subscribe");

    Route::get("/file/{file}" , "FileController@details")->name("file.details");
    Route::get("/file/download/{file}" , "FileController@download")->name("file.download");
    Route::post("/file/report" , "FileController@report")->name("file.report");

    Route::get("/package/{package}" , "PackageController@details")->name("package.details");
    Route::post("/package/{package}" , "PackageController@buy")->name("package.buy");

    Route::get("/categories/{category}" , "CategoryController@view")->name("categories.view");

	Route::get('/payment/{plan}' ,'PaymentController@RedirectTo')->name('payment.start');
    Route::post('/payment/mellat/verify' , 'PaymentController@verify')->name('gateway.mellat.verify');
});



Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Category
 *
 * @property int $id
 * @property string $name
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\File[] $files
 * @property-read int|null $files_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Package[] $packages
 * @property-read int|null $packages_count
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Category extends Model
{
	protected $fillable = ["name"];

	public function files()
	{
		return $this->morphedByMany(File::class,"categorizeable");
	}

	public function packages()
	{
		return $this->morphedByMany(Package::class,"categorizeable");
	}

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
	protected $rule = ["name" => "required"];
	public function index()
	{
		$categories = Category::all();
		return	view("Admin.Dashboard.Categories.Index")->with("categories" , $categories);
    }

	public function create()
	{
		return view("Admin.Dashboard.Categories.Create");
    }

	public function store(Request $request)
	{
		$request->validate($this ->rule);
		$categoryCreated = Category::create([
			'name'	=>  $request->input("name")
		]);

		if ($categoryCreated instanceof Category){
			return redirect()->route("admin.categories.list")->with(["success" => "دسته جدید {$categoryCreated->title} با موفقیت ثبت گردید."]);
		}
    }

    public function edit (Category $category){
		return view("Admin.Dashboard.Categories.Edit")->with("category" , $category);
	}

	public function update(Category $category , Request $request)
	{
		$request->validate($this->rule);

		$category->name = $request->input("name");
		$category->save();
		return redirect()->route("admin.categories.list")->with(["success" => "دسته  {$category->name} با موفقیت بروزرسانی گردید."]);
	}

	public function destroy(Category $category)
	{
		$name = $category->name;
		$category->delete();

		return redirect()->route("admin.categories.list")->with(["success" => "دسته   {$name} با موفقیت حذف گردید."]);
	}

}

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\UserDownload;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Intervention\Image\Facades\Image;
use Intervention\Image\ImageManager;

class DashboardController extends Controller
{
    public function index()
    {
    	$file = '/upload/Pictures/Untitledd.png';

    	dd(\App\Utility\File::GetFileSizeLink($file , 400));


        $DaysDownloads = UserDownload::DaysDownloads();

        return view("Admin.Dashboard.Index" , compact("DaysDownloads"));
    }
}

app/Http/Controllers/App/CategoryController.php
<?php

namespace App\Http\Controllers\App;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
	public function view(Category $category)
	{
		return view("App.Categories.View")->with(["category" => $category , "title" => "دسته {$category->name}"]);
    }
}

resources/views/Admin/Dashboard/Categories/CategoryItem.blade.php
<tr>
    <td>{{$category->id}}</td>
    <td>{{$category->name}}</td>
    <td style="text-align: center">
        <form action="{{route("admin.categories.delete" , $category)}}" method="post">
            @csrf
            @method("DELETE")
            <div class="btn-group">
                <a href="{{route("admin.categories.edit" , $category)}}" class="btn btn-success"><i class="glyphicon glyphicon-edit"></i></a>
                <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </td>
</tr>

resources/views/Admin/Dashboard/Categories/Create.blade.php
@extends("Layouts.Admin")
@section("content")
    <div class="panel panel-default">
        <div class="panel-heading">ثبت دسته جدید</div>
        <div class="panel-body">
            <div class="row">
                <form class="col-sx-12 col-md-6" action="{{route("admin.categories.store")}}" method="post">
                    @csrf
                    @include("Admin.Partials.Errors")
                    <div class="form-group">
                        <lable for="name">نام دسته:</lable>
                        <input type="text" name="name" id="name" placeholder="نام دسته..." class="form-control" value="{{old("name")}}">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-success" type="submit">ثبت</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/Admin/Dashboard/Categories/Edit.blade.php
@extends("Layouts.Admin")

@section("content")
    <?php
        global $CategoryData;
    $CategoryData = $category;
    function categoryData ($filed){
        global $CategoryData;
        if ( old($filed) == null){
            return $CategoryData->$filed;
        }
        return old($filed);
    }
    ?>
    <div class="panel panel-default">
        <div class="panel-heading">ویرایش پکیج</div>
        <div class="panel-body">
            <div class="row">
                <form class="col-sx-12 col-md-6"   action="{{route("admin.categories.update" , $category)}}" method="post">
                    @csrf
                    @method("PATCH")
                    @include("Admin.Partials.Errors")
                    <div class="form-group">
                        <lable for="name">نام دسته:</lable>
                        <input type="text" name="name" id="name" placeholder="نام دسته..." class="form-control" value="{{categoryData("name")}}">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-success" type="submit">ثبت</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/Admin/Dashboard/Categories/Index.blade.php
@extends("Layouts.Admin")
@section("content")
    <div class="panel panel-default">
        <div class="panel-heading">لیست پکیج ها</div>
        <div class="panel-body">
            @include("Admin.Partials.Notifications")
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>شناسه</td>
                        <td>نام دسته</td>
                        <td>عملیات</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach($categories as $category)
                        @include("Admin.Dashboard.Categories.CategoryItem" , $category)
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    </div>
@endsection

resources/views/Admin/Dashboard/Categories/SyncFiles.blade.php
@extends("Layouts.Admin")
@section("content")
    <div class="panel panel-default">
        <div class="panel-heading">ٍثبت فایل های پکیج</div>
        <div class="panel-body">
            <div class="row">
                <form class="col-sx-12 col-md-6" action="{{route("admin.packages.sync_file" , $package)}}" method="post">
                    @csrf
                    @include("Admin.Partials.Errors")
                    <div class="form-group">
                        <lable for="files">انتخاب فایل های پکیج:</lable>
                    </div>
                        <ul>
                            @foreach($files as $file)
                            <li>
                                <input type="checkbox" name="files[]" id="files"{{in_array($file->id , $packageFiles)?" checked" : ""}} value="{{$file->id}}">
                                {{$file->title}}
                            </li>
                            @endforeach
                        </ul>
                    <div class="form-group">
                        <button class="btn btn-success" type="submit">ثبت</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
@endsection