routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(["as" => "admin." , "namespace" => "Admin" , "prefix" => "admin/" , "middleware" => ["auth" , "admin"]],function (){

	Route::get("" , "DashboardController@index")->name("dashboard");

    //َAdmin Users Routes//
    Route::group(["as" => "users." , "prefix" => "users/"] , function () {
        Route::get("" , "UserController@index")->name("list");
        Route::get("create" , "UserController@create")->name("create");
        Route::post("create" , "UserController@store")->name("store");
        Route::get("{user}/edit" , "UserController@edit")->name("edit");
        Route::get("{user}/packages" , "UserController@packages_list")->name("packages");
        Route::patch("{user}/update" , "UserController@update")->name("update");
        Route::delete("{user}/delete" , "UserController@destroy")->name("delete");
    });

    //Admin Files Routes//
    Route::group(["as" => "files." , "prefix" => "files/"] , function () {
        Route::get("", "FileController@index")->name("list");
        Route::get("create", "FileController@create")->name("create");
        Route::post("create", "FileController@store")->name("store");
        Route::get("{file}/edit", "FileController@edit")->name("edit");
        Route::patch("{file}/update", "FileController@update")->name("update");
        Route::delete("{file}/delete", "FileController@destroy")->name("delete");
    });

    //Admin Plans Routes//
    Route::group(["as" => "plans." , "prefix" => "plans/"] , function () {
        Route::get("" , "PlanController@index")->name("list");
        Route::get("create" , "PlanController@create")->name("create");
        Route::post("create" , "PlanController@store")->name("store");
        Route::get("{plan}/edit" , "PlanController@edit")->name("edit");
        Route::patch("{plan}/update" , "PlanController@update")->name("update");
        Route::delete("{plan}/delete" , "PlanController@destroy")->name("delete");
    });

    //Admin Categories Routes//
    Route::group(["as" => "categories." , "prefix" => "categories/"] , function () {
        Route::get("" , "CategoryController@index")->name("list");
        Route::get("create" , "CategoryController@create")->name("create");
        Route::post("create" , "CategoryController@store")->name("store");
        Route::get("{category}/edit" , "CategoryController@edit")->name("edit");
        Route::patch("{category}/update" , "CategoryController@update")->name("update");
        Route::delete("{category}/delete" , "CategoryController@destroy")->name("delete");
    });

    //Admin Packages Routes//
    Route::group(["as" => "packages." , "prefix" => "packages/"] , function () {
        Route::get("" , "PackageController@index")->name("list");
        Route::get("create" , "PackageController@create")->name("create");
        Route::post("create" , "PackageController@store")->name("store");
        Route::get("{package}/edit" , "PackageController@edit")->name("edit");
        Route::patch("{package}/update" , "PackageController@update")->name("update");
        Route::delete("{package}/delete" , "PackageController@destroy")->name("delete");

        Route::get('sync_files/{package}', "PackageController@sync_file")->name("sync_file_view");
        Route::post('sync_files/{package}', "PackageController@sync")->name("sync_file");
    });

    //Admin Plans Routes//
    Route::group(["as" => "payments." , "prefix" => "payments/"] , function () {
        Route::get("", "PaymentController@index")->name("list");
    });
});

Auth::routes();
Route::group(["as" => "app." , "namespace" => "App"] , function (){
	Route::middleware('guest')->group(function (){
	Route::get("Account/login" ,"AuthController@loginView")->name("login.view");
	Route::get("Account/register" ,"AuthController@registerView")->name("register.view");
	Route::post("Account/login" ,"AuthController@login")->name("login.action");
	Route::post("Account/register" ,"AuthController@register")->name("register.action");
});
	Route::get("Account/logout" ,"AuthController@logout")->name("logout.action");

    Route::get("" , "HomeController@index")->name("home");

    Route::get("/plans" , "PlanController@index")->name("plans.index");

    Route::get("/subscribe/{plan}" , "SubscribeController@subscribe")->name("subscribes.subscribe");

    Route::get("/file/{file}" , "FileController@details")->name("file.details");
    Route::get("/file/download/{file}" , "FileController@download")->name("file.download");
    Route::post("/file/report" , "FileController@report")->name("file.report");

    Route::get("/package/{package}" , "PackageController@details")->name("package.details");
    Route::post("/package/{package}" , "PackageController@buy")->name("package.buy");

    Route::get("/categories/{category}" , "CategoryController@view")->name("categories.view");

	Route::get('/payment/{plan}' ,'PaymentController@RedirectTo')->name('payment.start');
    Route::post('/payment/mellat/verify' , 'PaymentController@verify')->name('gateway.mellat.verify');
});



Route::get('/home', 'HomeController@index')->name('home');

app/File.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\File
 *
 * @property int $id
 * @property string $title
 * @property string $name
 * @property string $description
 * @property string $type
 * @property int $size
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property int $report_count
 * @property int $download_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\User[] $DownloadMeUsers
 * @property-read int|null $download_me_users_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Category[] $categories
 * @property-read int|null $categories_count
 * @property-read mixed $file_type
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Package[] $packages
 * @property-read int|null $packages_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\User[] $usersDownloaded
 * @property-read int|null $users_downloaded_count
 * @method static \Illuminate\Database\Eloquent\Builder|\App\File newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\File newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\File query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\File whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\File whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\File whereDownloadCount($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\File whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\File whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\File whereReportCount($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\File whereSize($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\File whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\File whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\File whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class File extends Model
{
    protected $fillable = [
        "title" , "name" , "description" ,"type" , "size" , "report_count"
    ];
	/**
	 * @var mixed
	 */

	public function packages()
    {
        return $this->belongsToMany(Package::class);
    }

	public function categories()
	{
		return $this->morphToMany(Category::class,"categorizeable");
    }

    public function getFileTypeAttribute()
    {
        preg_match("/[a-zA-Z0-9]+$/" , $this->attributes["name"] , $fileType);

        return $fileType[0];
    }

	public static function PopulerDownloaded()
	{
		return File::orderBy("download_count" , "desc")->limit(5)->get();
    }

	public function usersDownloaded()
	{
		return $this->belongsToMany(User::class , UserDownload::class)->withPivot("download_date");
    }

    public function DownloadMeUsers()
    {
        return $this->belongsToMany(User::class , "user_downloads")->withPivot("download_date");
    }
}

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\UserDownload;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Intervention\Image\Facades\Image;
use Intervention\Image\ImageManager;

class DashboardController extends Controller
{
    public function index()
    {
    	$file = '/upload/Pictures/Untitledd.png';

    	dd(\App\Utility\File::GetFileSizeLink($file , 400));


        $DaysDownloads = UserDownload::DaysDownloads();

        return view("Admin.Dashboard.Index" , compact("DaysDownloads"));
    }
}

app/Http/Controllers/Admin/FileController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class FileController extends Controller
{
    public function index()
    {
        $files = File::all();
        return view("Admin.Dashboard.Files.Index")->with("files" , $files);
    }

    public function store(Request $request)
    {
        $request->validate([
            "title" => "required",
            "fileData" => "required",
            "categories" => "required|array"
        ],[
            "fileData.required" => "آپلود کردن فایل الزامی است",
            "categories.required" => "انتخاب دسته الزامی است.",
            "categories.array" => "دسته ها باید به صورت آرایه ارسال گردند."
        ]);

        $file = $request->file('fileData');
        $name = $file->getClientOriginalName();
		preg_match('/^(.*)(\.(.*))$/', $name , $matchs);
		\App\Utility\File::Upload($file , [300,600]);
        $file = $file->move(storage_path('upload\files') , $file->hashName());
        if ($file instanceof \Symfony\Component\HttpFoundation\File\File){
            $fileData =  File::create([
                'title'         =>  $request->input("title"),
                'description'   =>  $request->input("description") ? $request->input("description") : " ",
                'type'          =>  $file->getMimeType(),
                'size'          =>  $file->getSize(),
                'name'          =>  $file->getBasename()
            ]);
            $fileData->categories()->sync($request->input("categories"));
            return redirect()->route('admin.files.list')->with('success' , "فایل ( {$fileData->title} ) با موفقیت ثبت گردید.");
        }
        return back();
    }

    public function create()
    {
    	$categories = Category::all();
        return view("Admin.Dashboard.Files.Create")->with("categories" , $categories);
    }

    public function edit(File $file)
    {
        $categories = Category::all();
        return view("Admin.Dashboard.Files.Edit")->with(['file' => $file , "categories" => $categories]);
    }

    public function update(File $file , Request $request)
    {
        $request->validate([
            "title" => "required",
            "categories" => "required|array"
        ],[
            "categories.required" => "انتخاب دسته الزامی است.",
            "categories.array" => "دسته ها باید به صورت آرایه ارسال گردند."
        ]);
        $fileData = [
            'title'         =>  $request->input("title"),
            'description'   =>  $request->input("description") ? $request->input("description") : " "
            ];
        if ($request->file('fileData')) {
            $fileUploaded = $request->file('fileData');
            \App\Utility\File::Upload($fileUploaded , [300,600,1900]);
            $fileUploaded = $fileUploaded->move(storage_path('upload\files'), $fileUploaded->hashName());
            if ($fileUploaded instanceof \Symfony\Component\HttpFoundation\File\File) {
            	$existFile = Storage::disk('upload')->exists("/files/".$file->name);
                $delFile = Storage::disk('upload')->delete('files/' . $file->name);
                if ($delFile == true or  $existFile == false){
                    $fileData['type'] = $fileUploaded->getMimeType();
                    $fileData['size'] = $fileUploaded->getSize();
                    $fileData['name'] = $fileUploaded->getBasename();
                }
            }
        }
        $file->update($fileData);
        $file->categories()->sync($request->input("categories"));
        return redirect()->route('admin.files.list')->with('success' , "فایل ( {$request->input("title")} ) با موفقیت آپدیت شد.");
    }

    public function destroy(File $file)
    {
         $delFile = Storage::disk('upload')->delete('files/'.$file->name);
         if ($delFile == true){
             $fileTitle = $file->title;
             $file->delete();
             return back()->with("success" , "فایل ( {$fileTitle} ) با موفقیت حذف گردید.");
         }
    }
}

app/Http/Controllers/Api/V1/App/FileController.php
<?php

namespace App\Http\Controllers\Api\v1\App;

use App\File;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class FileController extends Controller
{
	public function Details(File $file)
	{
		$file->__set("FileType" , $file->file_type);

		return $file;
    }
}

app/Http/Controllers/App/FileController.php
<?php

namespace App\Http\Controllers\App;

use App\File;
use App\Http\Controllers\Controller;
use App\Subscribe;
use App\Utility\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class FileController extends Controller
{
    public function details(File $file)
    {
        return view("App.File.Details")->with(["file" => $file , "title" => "جزئیات فایل {$file->title}"]);
    }

    public function download(File $file)
    {
        $user = Auth::user();
        $f = \App\Utility\File::CanDownload($user,$file);
        if ($f){
            $fileDirectory = storage_path("upload").'\files\\';
            $filePath = $fileDirectory.$file->name;
            if (Storage::disk("upload")->exists('\files\\'.$file->name)){
                if ($f instanceof Subscribe) {
                    if (!User::DownloadableToday($user,$file)){
                        return back();
                    }
                    $f->increment("download_count");
                }
				$file->DownloadMeUsers()->attach($user , ["download_date" => Carbon::now()]);
				$file->increment("download_count");
                return response()->download($filePath);
            }
            return back();
        }
        return back();
    }

    public function report(Request $request)
    {
        $file = File::find($request->fid);
        $res =  $file->increment("report_count");
        if (is_integer($res)){
            return response()->json(["type" => "success" , "message" => "گذارش شما با موفقیت ثبت گردید." , "title" => "موفق"]);
        }else{
            return response()->json(["type" => "error" , "message" => "عملیا ثبت گذارش با خطا مواجه شد!" , "title" => "خطا!"]);
        }
    }
}

resources/views/Admin/Dashboard/Files/Create.blade.php
@extends("Layouts.Admin")
@section("content")
    <div class="panel panel-default">
        <div class="panel-heading">ثبت فایل جدید</div>
        <div class="panel-body">
            <div class="row">
                <form class="col-sx-12 col-md-6" action="{{route("admin.files.store")}}" method="post" enctype="multipart/form-data">
                    @csrf
                    @include("Admin.Partials.Errors")
                    <div class="form-group">
                        <lable for="title">عنوان فایل:</lable>
                        <input type="text" name="title" id="title" placeholder="عنوان فایل..." class="form-control" value="{{old("title")}}">
                    </div>
                    <div class="form-group">
                        <lable for="description">توضیحات:</lable>
                        <textarea name="description" id="description" placeholder="توضیحات..." class="form-control">{{old("description")}}</textarea>
                    </div>
                    <div class="form-group">
                        <lable for="categories">انتخاب دسته:</lable>
                        <select name="categories[]" id="categories" class="form-control" multiple>
                            @foreach($categories as $category)
                            <option value="{{$category->id}}" {{is_array(old("categories"))  && in_array($category->id , old("categories")) ? "selected" : ""}}>{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <lable for="file">انتخاب فایل:</lable>
                        <input type="file" name="fileData" id="file" placeholder="انتخاب فایل..." class="form-control">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-success" type="submit">ثبت</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
@endsection
@section("pageScript")
    <script>
        $(document).ready(function () {
            $("#categories").select2({
                dir: "rtl"
            });
        })
    </script>
@endsection

resources/views/Admin/Dashboard/Files/Edit.blade.php
@extends("Layouts.Admin")

@section("content")
    <?php
        global $FileData;
        $FileData = $file;
    function fileData ($filed){
        global $FileData;
        if ( old($filed) == null){
            if ($filed === "categories"){
                return $FileData->categories()->pluck("id")->toArray();
            }
            return $FileData->$filed;
        }
        return old($filed);
    }
    ?>
    <div class="panel panel-default">
        <div class="panel-heading">ویرایش فایل</div>
        <div class="panel-body">
            <div class="row">
                <form class="col-sx-12 col-md-6" action="{{route("admin.files.update" , $file)}}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method("PATCH")
                    @include("Admin.Partials.Errors")
                    <div class="form-group">
                        <lable for="title">عنوان فایل:</lable>
                        <input type="text" name="title" id="title" placeholder="عنوان فایل..." class="form-control" value="{{fileData("title")}}">
                    </div>
                    <div class="form-group">
                        <lable for="description">توضیحات:</lable>
                        <textarea name="description" id="description" placeholder="توضیحات..." class="form-control">{{fileData("description")}}</textarea>
                    </div>
                    <div class="form-group">
                        <lable for="categories">انتخاب دسته:</lable>
                        <select name="categories[]" id="categories" class="form-control" multiple>
                            @foreach($categories as $category)
                                <option value="{{$category->id}}" {{is_array(fileData("categories"))  && in_array($category->id , fileData("categories")) ? "selected" : ""}}>{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <lable for="file">انتخاب فایل:</lable>
                        <input type="file" name="fileData" id="file" placeholder="انتخاب فایل..." class="form-control">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-success" type="submit">ثبت</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
@endsection

@section("pageScript")
    <script>
        $(document).ready(function () {
            $("#categories").select2({
                dir: "rtl"
            });
        })
    </script>
@endsection

resources/views/Admin/Dashboard/Files/FileItem.blade.php
<tr>
    <td>{{$file->id}}</td>
    <td>{{$file->title}}</td>
    <td>{{$file->name}}</td>
    <td>{{$file->type}}</td>
    <td>{{$file->size}}</td>
    <td style="text-align: center">
        <form action="{{route("admin.files.delete" , $file)}}" method="post">
            @csrf
            @method("DELETE")
            <div class="btn-group">
                <a href="{{route("admin.files.edit" , $file)}}" class="btn btn-success"><i class="glyphicon glyphicon-edit"></i></a>
                <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </td>
</tr>

resources/views/Admin/Dashboard/Files/Index.blade.php
@extends("Layouts.Admin")
@section("content")
    <div class="panel panel-default">
        <div class="panel-heading">لیست فایل ها</div>
        <div class="panel-body">
            @include("Admin.Partials.Notifications")
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>شناسه</td>
                        <td>عنوان فایل</td>
                        <td>نام فایل</td>
                        <td>نوع فایل</td>
                        <td>اندازه فایل</td>
                        <td>عملیات</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach($files as $file)
                        @include("Admin.Dashboard.Files.FileItem" , $file)
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    </div>
@endsection