routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(["as" => "admin." , "namespace" => "Admin" , "prefix" => "admin/" , "middleware" => ["auth" , "admin"]],function (){

	Route::get("" , "DashboardController@index")->name("dashboard");

    //َAdmin Users Routes//
    Route::group(["as" => "users." , "prefix" => "users/"] , function () {
        Route::get("" , "UserController@index")->name("list");
        Route::get("create" , "UserController@create")->name("create");
        Route::post("create" , "UserController@store")->name("store");
        Route::get("{user}/edit" , "UserController@edit")->name("edit");
        Route::get("{user}/packages" , "UserController@packages_list")->name("packages");
        Route::patch("{user}/update" , "UserController@update")->name("update");
        Route::delete("{user}/delete" , "UserController@destroy")->name("delete");
    });

    //Admin Files Routes//
    Route::group(["as" => "files." , "prefix" => "files/"] , function () {
        Route::get("", "FileController@index")->name("list");
        Route::get("create", "FileController@create")->name("create");
        Route::post("create", "FileController@store")->name("store");
        Route::get("{file}/edit", "FileController@edit")->name("edit");
        Route::patch("{file}/update", "FileController@update")->name("update");
        Route::delete("{file}/delete", "FileController@destroy")->name("delete");
    });

    //Admin Plans Routes//
    Route::group(["as" => "plans." , "prefix" => "plans/"] , function () {
        Route::get("" , "PlanController@index")->name("list");
        Route::get("create" , "PlanController@create")->name("create");
        Route::post("create" , "PlanController@store")->name("store");
        Route::get("{plan}/edit" , "PlanController@edit")->name("edit");
        Route::patch("{plan}/update" , "PlanController@update")->name("update");
        Route::delete("{plan}/delete" , "PlanController@destroy")->name("delete");
    });

    //Admin Categories Routes//
    Route::group(["as" => "categories." , "prefix" => "categories/"] , function () {
        Route::get("" , "CategoryController@index")->name("list");
        Route::get("create" , "CategoryController@create")->name("create");
        Route::post("create" , "CategoryController@store")->name("store");
        Route::get("{category}/edit" , "CategoryController@edit")->name("edit");
        Route::patch("{category}/update" , "CategoryController@update")->name("update");
        Route::delete("{category}/delete" , "CategoryController@destroy")->name("delete");
    });

    //Admin Packages Routes//
    Route::group(["as" => "packages." , "prefix" => "packages/"] , function () {
        Route::get("" , "PackageController@index")->name("list");
        Route::get("create" , "PackageController@create")->name("create");
        Route::post("create" , "PackageController@store")->name("store");
        Route::get("{package}/edit" , "PackageController@edit")->name("edit");
        Route::patch("{package}/update" , "PackageController@update")->name("update");
        Route::delete("{package}/delete" , "PackageController@destroy")->name("delete");

        Route::get('sync_files/{package}', "PackageController@sync_file")->name("sync_file_view");
        Route::post('sync_files/{package}', "PackageController@sync")->name("sync_file");
    });

    //Admin Plans Routes//
    Route::group(["as" => "payments." , "prefix" => "payments/"] , function () {
        Route::get("", "PaymentController@index")->name("list");
    });
});

Auth::routes();
Route::group(["as" => "app." , "namespace" => "App"] , function (){
	Route::middleware('guest')->group(function (){
	Route::get("Account/login" ,"AuthController@loginView")->name("login.view");
	Route::get("Account/register" ,"AuthController@registerView")->name("register.view");
	Route::post("Account/login" ,"AuthController@login")->name("login.action");
	Route::post("Account/register" ,"AuthController@register")->name("register.action");
});
	Route::get("Account/logout" ,"AuthController@logout")->name("logout.action");

    Route::get("" , "HomeController@index")->name("home");

    Route::get("/plans" , "PlanController@index")->name("plans.index");

    Route::get("/subscribe/{plan}" , "SubscribeController@subscribe")->name("subscribes.subscribe");

    Route::get("/file/{file}" , "FileController@details")->name("file.details");
    Route::get("/file/download/{file}" , "FileController@download")->name("file.download");
    Route::post("/file/report" , "FileController@report")->name("file.report");

    Route::get("/package/{package}" , "PackageController@details")->name("package.details");
    Route::post("/package/{package}" , "PackageController@buy")->name("package.buy");

    Route::get("/categories/{category}" , "CategoryController@view")->name("categories.view");

	Route::get('/payment/{plan}' ,'PaymentController@RedirectTo')->name('payment.start');
    Route::post('/payment/mellat/verify' , 'PaymentController@verify')->name('gateway.mellat.verify');
});



Route::get('/home', 'HomeController@index')->name('home');

app/Package.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Package
 *
 * @property int $id
 * @property string $title
 * @property int $price
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Category[] $categories
 * @property-read int|null $categories_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\File[] $files
 * @property-read int|null $files_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\User[] $users
 * @property-read int|null $users_count
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Package newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Package newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Package query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Package whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Package whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Package wherePrice($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Package whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Package whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Package extends Model
{
    protected $fillable = [
        "title" , "price"
    ];

    public function files()
    {
        return $this->belongsToMany(File::class);
    }

	public function users()
	{
		return $this->belongsToMany(User::class)->withPivot(["amount" , "created_at"]);
	}

	public function categories()
	{
		return $this->morphToMany(Category::class,"categorizeable");
	}
}

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\UserDownload;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Intervention\Image\Facades\Image;
use Intervention\Image\ImageManager;

class DashboardController extends Controller
{
    public function index()
    {
    	$file = '/upload/Pictures/Untitledd.png';

    	dd(\App\Utility\File::GetFileSizeLink($file , 400));


        $DaysDownloads = UserDownload::DaysDownloads();

        return view("Admin.Dashboard.Index" , compact("DaysDownloads"));
    }
}

app/Http/Controllers/Admin/PackageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\File;
use App\Http\Controllers\Controller;
use App\Package;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class PackageController extends Controller
{
    protected $rule = [
        "title" => "required|max:150|min:5",
        "price" => "required|numeric",
    ];
    public function index()
    {
        $packages = Package::all();
        return view("Admin.Dashboard.packages.Index" )->with(["packages" => $packages]);
    }

    public function create()
    {
		$categories = Category::all();
        return view("Admin.Dashboard.packages.Create")->with("categories" , $categories);
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate($this ->rule , [
            "price.required" => "قیمت الزامی است.",
            "price.numeric" => "قیمت باید عدد یا رشته‌ای از اعداد باشد.",
			"categories" => "required|array",
        ],[
			"categories.required" => "انتخاب دسته الزامی است.",
			"categories.array" => "دسته ها باید به صورت آرایه ارسال گردند."
		]);
        $packageCreated = Package::create([
            'title'                  =>  $request->input("title"),
            'price'                  =>  $request->input("price"),
        ]);
		$packageCreated->categories()->sync($request->input("categories"));
        if ($packageCreated instanceof Package){
            return redirect()->route("admin.packages.list")->with(["success" => "پکیج جدید {$packageCreated->title} با موفقیت ثبت گردید."]);
        }
    }

    public function edit(Package $package)
    {
		$categories = Category::all();
        return view("Admin.Dashboard.packages.Edit" )->with(["package" => $package , "categories" => $categories]);
    }

    public function update(Package $package , Request $request)
    {
        $request->validate($this ->rule , [
            "price.required" => "قیمت الزامی است.",
            "price.numeric" => "قیمت باید عدد یا رشته‌ای از اعداد باشد.",
			"categories" => "required|array",
        ],[
			"categories.required" => "انتخاب دسته الزامی است.",
			"categories.array" => "دسته ها باید به صورت آرایه ارسال گردند."
		]);

        $package->title  =  $request->input("title");
        $package->price  =  $request->input("price");
        $package->save();
		$package->categories()->sync($request->input("categories"));
        return redirect()->route("admin.packages.list")->with(["success" => "پکیج  {$package->name} با موفقیت بروزرسانی گردید."]);
    }

    public function destroy(Package $package)
    {
        $title = $package->title;
        $package->delete();
        return redirect()->route("admin.packages.list")->with(["success" => "پکیج   {$title} با موفقیت حذف گردید."]);
    }

	public function sync_file(Package $package)
	{
		$files = File::all();
		$packageFiles = $package->files()->pluck("id")->toArray();
		return view("Admin.Dashboard.Packages.SyncFiles")->with(["files" => $files , "package" => $package , "packageFiles" => $packageFiles]);
    }

	public function sync(Package $package , Request $request)
	{
		$filesSelected = $request->input("files");

		$package->files()->sync($filesSelected);

		return redirect()->route("admin.packages.list")->with("success" , "فایل های پکیج ( {$package->title} ) با موفقیت ثبت گردید.");
    }
}

app/Http/Controllers/App/PackageController.php
<?php

namespace App\Http\Controllers\App;

use App\Http\Controllers\Controller;
use App\Package;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PackageController extends Controller
{
    public function details(Package $package)
    {

        return view("App.Package.Details")->with(["package" => $package , "title" => $package->title]);
    }

    public function buy(Package $package)
    {
        if (!Auth::check()){
            return redirect()->route("app.login.view");
        }
        Auth::user()->packages()->attach($package , ["amount" => $package->price]);
        return back();
    }
}

resources/views/Admin/Dashboard/Packages/Create.blade.php
@extends("Layouts.Admin")
@section("content")
    <div class="panel panel-default">
        <div class="panel-heading">ثبت پکیج جدید</div>
        <div class="panel-body">
            <div class="row">
                <form class="col-sx-12 col-md-6" action="{{route("admin.packages.store")}}" method="post">
                    @csrf
                    @include("Admin.Partials.Errors")
                    <div class="form-group">
                        <lable for="title">عنوان پکیج:</lable>
                        <input type="text" name="title" id="title" placeholder="عنوان..." class="form-control" value="{{old("title")}}">
                    </div>
                    <div class="form-group">
                        <lable for="price">قیمت:</lable>
                        <input type="number" name="price" id="price" placeholder="قیمت..." class="form-control" value="{{old("price")}}">
                    </div>
                    <div class="form-group">
                        <lable for="categories">انتخاب دسته:</lable>
                        <select name="categories[]" id="categories" class="form-control" multiple>
                            @foreach($categories as $category)
                                <option value="{{$category->id}}" {{is_array(old("categories"))  && in_array($category->id , old("categories")) ? "selected" : ""}}>{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-success" type="submit">ثبت</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
@endsection
@section("pageScript")
    <script>
        $(document).ready(function () {
            $("#categories").select2({
                dir: "rtl"
            });
        })
    </script>
@endsection

resources/views/Admin/Dashboard/Packages/Edit.blade.php
@extends("Layouts.Admin")

@section("content")
    <?php
        global $PackageData;
    $PackageData = $package;
    function packageData ($filed){
        global $PackageData;
        if ( old($filed) == null){
            if ($filed === "categories"){
                return $PackageData->categories()->pluck("id")->toArray();
            }
            return $PackageData->$filed;
        }
        return old($filed);
    }
    ?>
    <div class="panel panel-default">
        <div class="panel-heading">ویرایش پکیج</div>
        <div class="panel-body">
            <div class="row">
                <form class="col-sx-12 col-md-6"   action="{{route("admin.packages.update" , $package)}}" method="post">
                    @csrf
                    @method("PATCH")
                    @include("Admin.Partials.Errors")
                    <div class="form-group">
                        <lable for="title">عنوان پکیج:</lable>
                        <input type="text" name="title" id="title" placeholder="عنوان..." class="form-control" value="{{packageData("title")}}">
                    </div>
                    <div class="form-group">
                        <lable for="price">قیمت:</lable>
                        <input type="number" name="price" id="price" placeholder="قیمت..." class="form-control" value="{{packageData("price")}}">
                    </div>
                    <div class="form-group">
                        <lable for="categories">انتخاب دسته:</lable>
                        <select name="categories[]" id="categories" class="form-control" multiple>
                            @foreach($categories as $category)
                                <option value="{{$category->id}}" {{is_array(packageData("categories"))  && in_array($category->id , packageData("categories")) ? "selected" : ""}}>{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-success" type="submit">ثبت</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
@endsection

@section("pageScript")
    <script>
        $(document).ready(function () {
            $("#categories").select2({
                dir: "rtl"
            });
        })
    </script>
@endsection

resources/views/Admin/Dashboard/Packages/Index.blade.php
@extends("Layouts.Admin")
@section("content")
    <div class="panel panel-default">
        <div class="panel-heading">لیست پکیج ها</div>
        <div class="panel-body">
            @include("Admin.Partials.Notifications")
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>شناسه</td>
                        <td>عنوان</td>
                        <td>قیمت</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach($packages as $package)
                        @include("Admin.Dashboard.Packages.PackageItem" , $package)
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    </div>
@endsection

resources/views/Admin/Dashboard/Packages/PackageItem.blade.php
<tr>
    <td>{{$package->id}}</td>
    <td>{{$package->title}}</td>
    <td>{{$package->price}}</td>
    <td style="text-align: center">
        <form action="{{route("admin.packages.delete" , $package)}}" method="post">
            @csrf
            @method("DELETE")
            <div class="btn-group">
                <a href="{{route("admin.packages.sync_file" , $package)}}" class="btn btn-info"><i class="glyphicon glyphicon-file"></i></a>
                <a href="{{route("admin.packages.edit" , $package)}}" class="btn btn-success"><i class="glyphicon glyphicon-edit"></i></a>
                <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </td>
</tr>

resources/views/Admin/Dashboard/Packages/SyncFiles.blade.php
@extends("Layouts.Admin")
@section("content")
    <div class="panel panel-default">
        <div class="panel-heading">ٍثبت فایل های پکیج</div>
        <div class="panel-body">
            <div class="row">
                <form class="col-sx-12 col-md-6" action="{{route("admin.packages.sync_file" , $package)}}" method="post">
                    @csrf
                    @include("Admin.Partials.Errors")
                    <div class="form-group">
                        <lable for="files">انتخاب فایل های پکیج:</lable>
                    </div>
                        <ul>
                            @foreach($files as $file)
                            <li>
                                <input type="checkbox" name="files[]" id="files"{{in_array($file->id , $packageFiles)?" checked" : ""}} value="{{$file->id}}">
                                {{$file->title}}
                            </li>
                            @endforeach
                        </ul>
                    <div class="form-group">
                        <button class="btn btn-success" type="submit">ثبت</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
@endsection